export const GenderOptions = ["Male", "Female", "Other"];

export const PatientFormDefaultValues = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  birthDate: new Date(Date.now()),
  gender: "Male" as Gender,
  address: "",
  occupation: "",
  emergencyContactName: "",
  emergencyContactNumber: "",
  primaryPhysician: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "None",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};

export const IdentificationTypes = [
  "None",
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Aadhaar Card",
  "State ID Card",
  "Student ID Card",
  "Pan Card",
  "Voter ID Card",
];

export const Doctors = [
  {
    image: "/assets/images/dr-green.png",
    name: "Raj Kapoor",
    specialty: "Cardiologist",
    title: "Senior Consultant",
    email: "raj.kapoor@careplus.com",
  },
  {
    image: "/assets/images/dr-cameron.png",
    name: "Ishita Mehta",
    specialty: "Neurologist",
    title: "Consultant",
    email: "ishita.mehta@careplus.com",
  },
  {
    image: "/assets/images/dr-livingston.png",
    name: "Vivaan Reddy",
    specialty: "Orthopedist",
    title: "Consultant",
    email: "vivaan.reddy@careplus.com",
  },
  {
    image: "/assets/images/dr-peter.png",
    name: "Aditya Singh",
    specialty: "Ophthalmologist",
    title: "Senior Consultant",
    email: "aditya.singh@careplus.com",
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Diya Patel",
    specialty: "Dermatologist",
    title: "Consultant",
    email: "diya.patel@careplus.com",
  },
  {
    image: "/assets/images/dr-remirez.png",
    name: "Karan Malhotra",
    specialty: "Pediatrician",
    title: "Consultant",
    email: "karan.malhotra@careplus.com",
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Sneha Das",
    specialty: "Gastroenterologist",
    title: "Senior Consultant",
    email: "sneha.das@careplus.com",
  },
  {
    image: "/assets/images/dr-cruz.png",
    name: "Ananya Nair",
    specialty: "Psychiatrist",
    title: "Consultant",
    email: "ananya.nair@careplus.com",
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Rohan Deshmukh",
    specialty: "Urologist",
    title: "Consultant",
    email: "rohan.deshmukh@careplus.com",
  },
];

export const TestCatalog = [
  "None",
  "Blood Test",
  "CBC",
  "Lipid Profile",
  "Liver Function Test",
  "Kidney Function Test",
  "Thyroid Profile",
  "HbA1c",
  "Urine Analysis",
  "X-Ray",
  "CT Scan",
  "MRI",
  "Ultrasound",
  "ECG",
  "Echocardiogram",
  "Stress Test",
];

export const RecordCategories = [
  "None",
  "Clinical Note",
  "Lab Report",
  "Prescription",
  "Imaging Report",
  "Discharge Summary",
  "Test Order",
  "Referral",
  "Patient Upload",
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  cancelled: "/assets/icons/cancelled.svg",
};
